### PR TITLE
Keras-mnist with SKIL Deployment  

### PR DESCRIPTION
**Pull request by pcrete**
I have added **SKIL client demo** which will run **SKIL Service** on _existing deployments_.

Sample code here:
```python
work_space = get_workspace_by_id(skil_server, workspace_id)
experiment = get_experiment_by_id(work_space, experiment_id))
model = get_model_by_id(experiment, model_id)
model_deployment = skil_server.api.models(deployment_id=deployment_id)

service = Service(
    skil=skil_server,
    model=model,
    deployment=deployment,
    model_deployment=model_deployment
)
```

### CODE REVIEW

**Comment by maxpumperla** [comment]
@pcrete thanks for this contribution, very valuable. Can you please leave the flow of the README as it was before? New users don't have existing deployments, so we want the first example to be from scratch.

You can add your example in a new paragraph after "skil in 60 seconds". You can call it "working with existing deployments" or so.

**Comment by maxpumperla** [comment]
@pcrete while we're at it, would you mind making this line

```
model_deployment = skil_server.api.models(deployment_id=deployment_id)
```

a function in `deployments.py` called `get_deployment_by_id`? We try to hide `skil_server` top-level

**Comment by pcrete** [comment]
> @pcrete thanks for this contribution, very valuable. Can you please leave the flow of the README as it was before? New users don't have existing deployments, so we want the first example to be from scratch.
> 
> You can add your example in a new paragraph after "skil in 60 seconds". You can call it "working with existing deployments" or so.

Sure, I will change that.

**Comment by pcrete** [comment]
> @pcrete while we're at it, would you mind making this line
> 
> ```
> model_deployment = skil_server.api.models(deployment_id=deployment_id)
> ```
> a function in `deployments.py` called `get_deployment_by_id`? We try to hide `skil_server` top-level

I just found that I forgot this line:
```python
deployment = get_deployment_by_id(skil_server, deployment_id)
```
It means that `get_deployment_by_id` was already used for `deployment`

So, which function should I use for the `model_deployment` parameter in `skil.Service()`

```python
work_space = get_workspace_by_id(skil_server, workspace_id)
experiment = get_experiment_by_id(work_space, experiment_id))

model = get_model_by_id(experiment, model_id)
deployment = get_deployment_by_id(skil_server, deployment_id)

model_deployment = skil_server.api.models(deployment_id=deployment_id)

service = Service(
    skil=skil_server,
    model=model,
    deployment=deployment,
    model_deployment=model_deployment
)

```

**Comment by maxpumperla** [comment]
@pcrete ah, true. I checking this from my phone. If we already have that function, all the better: just use it. :D

**Pull request closed without merging**
